### ISSUE TITLE
Crash in LivingEntityMixin

### ISSUE THREAD

**Issue by coderbot16** [Blayyke/FabricToys#2]
LivingEntityMixin::ft_isSleepingInBed is missing a `cancellable=true` in the annotation, resulting in the following crash: https://paste.ee/p/0CLZh

Additionally, it appears the code on GitHub is outdated, which hid this error a bit... would it be possible to do a `git push` to sync the code on GH with your local code?

**Comment by Blayyke** [comment]
Fixed & pushed my current code. Thanks for pointing that out.

**Comment by coderbot16** [comment]
Great, thanks! 👍
